Сделал Sprint1
peeercyyy/beauty-world pull request #2
Opened 2021-10-17 10:14 UTC by peeercyyy

Сделал первый спринт
единственное при наведении курсором на кнопку "записаться онлайн" и на "Короткое видео о нас" у меня данные элементы выходят за границу, пока не могу понять как это пофиксить. Можете посоветовать как исправить?
И еще, содержимое кнопки "Развернуть" нужно было сделать в этом спринте? И что там вообще должно находиться?

2021-10-18 10:09 UTC, studenttsu requested changes
Привет! Хорошая работа! Есть моменты, которые нужно поправить

2021-10-18 10:09 UTC, studenttsu commented on index.html
>      <link rel="stylesheet" href="./main.css">
На занятии не сказал, но ваши стили нужно подключать ниже всех остальных подключаемых стилей. Ведь мы можем захотеть переопределить "внешние" стили

2021-10-18 10:09 UTC, studenttsu commented on index.html
> +                    <a href="tel:+74996861762" class="tel">8 (499) 686-17-62</a>
`отлично`

Удобно открывать набранный номер телефона на мобилке одним кликом

2021-10-18 10:09 UTC, studenttsu commented on index.html
> -                                <image id="image0" width="826" height="850" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAzoAAANSCAYAAACtFruDAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5c
`можно лучше`

Ссылкам, ведущих на внешние ресурсы нужно задавать атрибут target="_blank", чтобы ссылка открывалась в новой вкладк

2021-10-18 10:09 UTC, studenttsu commented on main.css
> +    overflow: hidden;
overflow: hidden; обрезает контент, который будет выходить за его пределы, поэтому при наведении на Видео о нас - часть карточки обрезается

2021-10-18 10:09 UTC, studenttsu commented on index.html
> -                                <image id="image0" width="826" height="850" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAzoAAANSCAYAAACtFruDAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5c
не совсем понял для какой цели `container__main`?

2021-10-18 10:09 UTC, studenttsu commented on index.html
> -                                <image id="image0" width="826" height="850" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAzoAAANSCAYAAACtFruDAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5c
по сути это отдельный самостоятельный блок, сейчас по названию класса он является элментом блока about-saloon

Это нарушает принципы именования по БЭМ

2021-10-18 10:09 UTC, studenttsu commented on main.css
> +    width: 350px;
Жесткие размеры не используем, контент должен подстраиваться под сетку родителя.

Если сейчас добавить описания много больше - потеряем контент

2021-10-18 10:09 UTC, studenttsu commented on main.css
> +.about-cabinets, .about-cosmetics, .about-masters {
почему бы не назвать одним именем? ведь это один и тот же блок, но с разным содержимым

2021-10-18 10:09 UTC, studenttsu commented on index.html
> +                            <p class="banner__subtitle">Идеальный образ за 60 минут</p>
Такие ситуации тоже нужно обрабатывать. Самый лучший способ - правильной разметкой
Хорошо бы описание слева завернуть в один контейнер и задать максимальную ширину

![image](https://user-images.githubusercontent.com/12005449/137711314-70ada550-22fd-49e0-99aa-137dce4a26d6.png)

2021-10-18 10:10 UTC, studenttsu commented
Содержимое кнопки развернуть будем делать в след. спринтах. Там будет появляться произвольный текст

2021-10-21 15:41 UTC, peeercyyy commented on main.css
> +    overflow: hidden;
убрал overflow: hidden у данного контейнера
по началу не понял у какого элемента необходимо сделать псевдоэлемент, сейчас додумался, вроде стало лучше

2021-10-21 15:42 UTC, peeercyyy commented on index.html
> -                                <image id="image0" width="826" height="850" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAzoAAANSCAYAAACtFruDAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5c
исправил
потихоньку стараюсь вводить БЭМ в свой код

2021-10-21 15:43 UTC, peeercyyy commented on main.css
> +.about-cabinets, .about-cosmetics, .about-masters {
по началу была идея назвать одним именем, но почему-то передумал, сейчас исправил

2021-10-21 15:43 UTC, peeercyyy commented on index.html
> +                            <p class="banner__subtitle">Идеальный образ за 60 минут</p>
обернул banner__title и banner__subtitle в контейнер и задал ему ширину

2021-10-21 15:44 UTC, peeercyyy commented on index.html
> -                                <image id="image0" width="826" height="850" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAzoAAANSCAYAAACtFruDAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5c
я его добавил в самом начале, думал буду изменять через него стили, но он не пригодился и я забыл убрать

2021-10-21 15:48 UTC, peeercyyy commented
Исправил первый спринт 
актуализировать названия классов под БЭМ буду во втором спринте

2021-11-16 04:19 UTC, studenttsu approved these changes
Всё круто, работа принята!

2021-11-16 04:23 UTC, merged